import streamlit as st
import os
from core.agent_chain import get_agent_status


def render_preview(clone_html, data, shot_path,
                   agent_used="", agent_logs=None, chars=0):

    # Safety: unpack if tuple was accidentally passed
    if isinstance(clone_html, tuple):
        clone_html = clone_html

    if not clone_html or len(clone_html) < 100:
        st.error("⚠️ Clone HTML is empty. Check your API keys and try again.")
        return

    st.markdown("---")
    st.caption(
        f"⚡ Generated by **{agent_used}** | "
        f"Size: **{chars:,}** characters"
    )

    tab1, tab2, tab3, tab4 = st.tabs([
        "🖥️ Clone Preview",
        "📸 Original Screenshot",
        "📊 Extracted Data",
        "🤖 Agent Logs"
    ])

    # ── Tab 1: Clone Preview ──────────────────────────────────────────────
    with tab1:
        st.download_button(
            label="⬇️ Download HTML Clone",
            data=clone_html,
            file_name="clone.html",
            mime="text/html",
            use_container_width=False
        )
        st.components.v1.html(clone_html, height=1200, scrolling=True)
        with st.expander("🔍 View Raw Generated HTML"):
            st.code(clone_html[:6000], language="html")
            if len(clone_html) > 6000:
                st.caption(f"... {len(clone_html)-6000:,} more characters not shown")

    # ── Tab 2: Original Screenshot ────────────────────────────────────────
    with tab2:
        if shot_path and os.path.exists(shot_path):
            st.markdown("**Full-page screenshot of the original website:**")
            st.image(shot_path, use_container_width=True)
        else:
            st.info("📸 Screenshot unavailable — site may be JS-heavy or protected.")

    # ── Tab 3: Extracted Data ─────────────────────────────────────────────
    with tab3:
        st.markdown("### 📋 Page Analysis")
        col1, col2 = st.columns(2)

        with col1:
            st.markdown("**🏷️ Title**")
            st.code(data.get("title", "N/A"))

            st.markdown("**📝 Meta Description**")
            st.code(data.get("meta_desc") or "Not found")

            st.markdown("**🎨 Color Palette**")
            colors = data.get("colors", [])
            if colors:
                cols = st.columns(min(len(colors), 6))
                for i, c in enumerate(colors[:6]):
                    with cols[i]:
                        st.markdown(
                            f"<div style='background:{c};height:40px;"
                            f"border-radius:8px;border:1px solid #ddd'></div>"
                            f"<p style='font-size:.7rem;text-align:center;"
                            f"margin-top:4px'>{c}</p>",
                            unsafe_allow_html=True
                        )
            else:
                st.caption("No inline colors detected")

            st.markdown("**📏 Page Stats**")
            st.markdown(f"""
- Fetched HTML: `{data.get('html_length', 0):,}` bytes
- Clone size: `{chars:,}` chars
- Headings: `{len(data.get('headings', []))}`
- Nav links: `{len(data.get('nav_links', []))}`
- CTA buttons: `{len(data.get('buttons', []))}`
""")

        with col2:
            st.markdown("**📌 Headings Found**")
            for h in data.get("headings", [])[:12]:
                tag = h["tag"].upper()
                color_map = {"H1": "#667eea", "H2": "#764ba2", "H3": "#9e9e9e"}
                c = color_map.get(tag, "#333")
                st.markdown(
                    f"<div style='margin-bottom:6px'>"
                    f"<span style='background:{c};color:white;padding:2px 8px;"
                    f"border-radius:4px;font-size:.72rem;font-weight:600'>{tag}</span>"
                    f" {h['text']}</div>",
                    unsafe_allow_html=True
                )

            st.markdown("<br>", unsafe_allow_html=True)
            st.markdown("**🔘 CTA Buttons**")
            for b in data.get("buttons", []):
                st.markdown(
                    f"<span style='display:inline-block;background:#f0f4ff;"
                    f"border:1px solid #667eea;color:#667eea;padding:4px 14px;"
                    f"border-radius:999px;font-size:.82rem;margin:3px'>{b}</span>",
                    unsafe_allow_html=True
                )

        st.markdown("---")
        st.markdown("**🔗 Navigation Links**")
        link_data = [
            {"Text": l["text"], "Href": l["href"]}
            for l in data.get("nav_links", [])[:15]
        ]
        if link_data:
            st.dataframe(link_data, use_container_width=True, height=280)
        else:
            st.caption("No links detected")

    # ── Tab 4: A2A Agent Logs ─────────────────────────────────────────────
    with tab4:
        st.markdown("### 🤖 A2A Agent Chain Execution Log")
        st.caption("Each agent tried in order. Rate-limited agents are skipped and auto-recover.")

        if not agent_logs:
            st.info("No logs yet.")
            return

        status_colors = {
            "success":      ("#e8f5e9", "#4caf50", "✅"),
            "failed":       ("#ffebee", "#f44336", "❌"),
            "rate_limited": ("#fff3e0", "#ff9800", "⚠️"),
            "skipped":      ("#f5f5f5", "#9e9e9e", "⏭️"),
            "trying":       ("#fff8e1", "#ffc107", "🔄"),
        }

        for i, log in enumerate(agent_logs):
            status = log.get("status", "")
            bg, border, icon = status_colors.get(status, ("#fff", "#ccc", "❓"))
            duration_txt = f" | ⏱ {log.get('duration', 0)}s" if log.get("duration") else ""
            chars_txt    = f" | {log.get('chars', 0):,} chars" if log.get("chars") else ""
            detail       = log.get("reason", "") or ""

            st.markdown(
                f"<div style='background:{bg};border-left:4px solid {border};"
                f"border-radius:10px;padding:12px 16px;margin-bottom:8px'>"
                f"<b>{icon} {log.get('icon','')} Agent {i+1}: {log.get('agent','')}</b><br>"
                f"<span style='font-size:.83rem;color:#555'>"
                f"Role: {log.get('role','')} | Status: <b>{status}</b>"
                f"{duration_txt}{chars_txt}</span>"
                f"{'<br><span style=font-size:.8rem;color:#888>' + detail + '</span>' if detail else ''}"
                f"</div>",
                unsafe_allow_html=True
            )

        # Live health panel
        st.markdown("---")
        st.markdown("### 🏥 Live Agent Health")
        registry = get_agent_status()
        cols = st.columns(3)
        for i, (provider, s) in enumerate(registry.items()):
            with cols[i]:
                avail = s["available"]
                cd    = s["cooldown_until"]
                st.markdown(
                    f"<div style='background:{'#e8f5e9' if avail else '#fff3e0'};"
                    f"border-radius:12px;padding:14px;text-align:center'>"
                    f"<b>{'🟢' if avail else '🟡'} {s['label']}</b><br>"
                    f"<small>Calls: {s['calls']} | Errors: {s['errors']}</small><br>"
                    f"<small>{'✅ Available' if avail else f'⏳ Recovers at {cd}'}</small>"
                    f"</div>",
                    unsafe_allow_html=True
                )